Coot
dmlc/gluon-cv pull request #1549
Opened 2020-11-28 17:14 UTC by mzolfaghari

Removed pylint errors!

2020-11-29 18:59 UTC, bryanyzhu requested changes
Excellent PR, thank you for your contribution. Can you add a README file under `./scripts/vision-language/video-language/coot/README.md`? You can put some details there for users to reproduce the paper, e.g., the paper link, paper abstract, overview figure, how to prepare dataset, how to train, how to evaluate and where to download your trained models. That will make the PR self-contained. Thank you very much.

2020-11-29 18:59 UTC, bryanyzhu commented on brazil.code-workspace
> +{
Is there a reason why you include this file? If not necessary, can you remove it? Thank you.

2020-11-29 18:59 UTC, bryanyzhu commented on gluoncv/torch/model_zoo/action_recognition/i3d_slow.py
> -           'i3d_slow_resnet101_f16s4_kinetics700']
Can you recover `i3d_slow_resnet101_f16s4_kinetics700 `? We need it for this release.

2020-11-29 18:59 UTC, bryanyzhu commented on gluoncv/torch/model_zoo/model_store.py
> -    ('b5be1a2e32158748a7efc675081affd32006fe9a', 'i3d_slow_resnet101_f16s4_kinetics700'),
Same here, can you put this line back? Thanks.

2020-11-30 22:10 UTC, bryanyzhu commented
Hi, I saw that the number of changed files is `209` right now. Lots of network definitions and configurations become empty files. Maybe there are some Github issues (commit mismatch), could you fix this? Thank you.

2020-11-30 23:28 UTC, mzolfaghari commented
> Hi, I saw that the number of changed files is `209` right now. Lots of network definitions and configurations become empty files. Maybe there are some Github issues (commit mismatch), could you fix this? Thank you.

Thanks for pointing out this problem. There was an issue with the commit!

2020-12-29 19:53 UTC, bryanyzhu commented
It seems that the error comes from there is no h5py found on the CI machine. One solution we often use is to import h5py inside each function whenever you need it, but not in the code header. In this way, the import issue won't happen.

2021-01-05 21:19 UTC, bryanyzhu approved these changes
Awesome, the PR looks great to me. I have some final minor comments. Please address them and I will merge it. Thank you.

2021-01-05 21:19 UTC, bryanyzhu commented on brazil.code-workspace
> +{
Since GluonCV doesn't have this file `brazil.code-workspace ` before, I was wondering do we need it here?

2021-01-05 21:19 UTC, bryanyzhu commented on scripts/vision-language/video-language/coot/train_pytorch.py
> +    # spawn_workers(main_worker, cfg)
Please remove this commented line 147.

2021-01-05 21:19 UTC, bryanyzhu commented on scripts/vision-language/video-language/coot/README.md
> +MeanR |  MedR |    Sum
The formatting of this table may need adjustment. Right now, it doesn't have a table structure.

2021-01-05 21:19 UTC, bryanyzhu commented on scripts/vision-language/video-language/coot/README.md
> +<p align="center"><img src="misc/thumbnail.png" alt="Method" title="Method" /></p>
The `thumnail.png` is missing at this moment.

2021-01-06 17:24 UTC, merged