backbone shufflenet module
dmlc/gluon-cv pull request #1722
Opened 2021-12-29 02:37 UTC by 315386775

Reproduced shufflenet V1 & V2 module. 

reference ： https://github.com/megvii-model/ShuffleNet-Series

200 epoch res validation: err-top1=0.343221 err-top5=0.133362

2021-12-29 03:15 UTC, 315386775 commented
Resubmit

2022-01-06 20:22 UTC, bryanyzhu requested changes
Awesome PR. If you have trained weights, can you share the (1) model weights and (2) numbers on ImageNet with me? I will upload them to our model store. Thank you.

2022-01-06 20:22 UTC, bryanyzhu commented on README.md
> +# New backbone shufflenet module.
Please remove this training bash from README, we will add it later to docs page (https://cv.gluon.ai/model_zoo/classification.html). Thank you.

2022-01-06 20:33 UTC, bryanyzhu commented
Syntax check has failed, please fix these issues to move on. Let me know if you need any help, thanks.

2022-01-07 05:50 UTC, 315386775 commented
@bryanyzhu thanks. this is my first time to contribute. i want to know :
a. i can share the trained model weights and train logs. where can i upload this files？
b. Syntax check has failed. maybe i need your help. i have pulled the new gluoncv version.

2022-01-07 19:44 UTC, bryanyzhu commented
> @bryanyzhu thanks. this is my first time to contribute. i want to know : a. i can share the trained model weights and train logs. where can i upload this files？ b. i have fixed the error according to the action logs.

A. You can upload your bash/models/logs to any cloud service, like google drive, onedrive, dropbox, and let me know the link. I will then upload them to our own S3 server. 

B. Thank you for fixing the errors. It seems that there are still some warnings. If you click on the red check again, it says (1) several lines are too long (2) trailing white space (3) and bad white space. 

Regarding (1), you can simply add `# pylint: disable=line-too-long` to the beginning of file (sth like [here](https://github.com/dmlc/gluon-cv/blob/ab03ca04c588342be5cd659c3f96011c0146ac4f/gluoncv/utils/compress_json.py#L1)). This will ignore the warning. 

Regarding (2), you can just remove the extra white spaces in the end of that line (shufflenet.py:120:0: C0303: Trailing whitespace (trailing-whitespace))

Regarding (3), you can remove the bad white space after `print` (shufflenet.py:204:14: C0326: No space allowed before bracket print ('x:', x))

Hope this will pass the syntax test.

2022-01-09 05:01 UTC, bryanyzhu approved these changes

2022-01-09 05:01 UTC, merged

2022-01-10 02:04 UTC, 315386775 commented
@bryanyzhu i have upload the bash/models/logs to dropbox. Link:
[https://www.dropbox.com/sh/8j2lry46msdvzsf/AACzkZEInYMEaAmd3sCNTXIua?dl=0](url)

Hyperparameters can continue to be adjusted, and I will continue to follow up.